### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by eyaleizenberg** [iltempo/sublime-text-2-hash-syntax#1]
Hi,
I really love your plugin. Can you please also make it compatible with the new sublime text 3? I installed the package but nothing happens when I hit cmd + ctr + h

Thanks a lot!!!

**Comment by iltempo** [comment]
I have a hard time finding documentation on what changes for Sublime Text 3. As soon as that's available I will update the plugin to be compatible.

**Comment by eyaleizenberg** [comment]
Thanks!

**Comment by bigardone** [comment]
+1 to this request :)

**Comment by murphyslaw** [comment]
+1

**Comment by eyaleizenberg** [comment]
Any progress on this?
Does this help: https://www.sublimetext.com/docs/3/api_reference.html

I will gladly buy you a beer if you do this soon ;)

Thanks!

**Comment by iltempo** [comment]
@eyaleizenberg Your last message was containing the _magic_ word. ;-)

I finally found the reason for the incompatibility. Funny enough it did not lie in the code but in the name of the plugin itself. I had to change it. The pull request has been sent to package control. 
https://github.com/wbond/package_control_channel/pull/1400

As soon as it got merged you have to do the following:
- Remove the _Ruby 1.9 Hash Converter_ plugin
- Install the _Ruby Hash Converter_ plugin

Everything else works as usual.

**Comment by eyaleizenberg** [comment]
Awesome! Thank you so much!

**Comment by eyaleizenberg** [comment]
Oh, and where do I send the beer? ;)

**Comment by iltempo** [comment]
How about `:beer:`?

**Comment by gsmetal** [comment]
I think, something has changed in Package Control repositories system and your changes were lost:
https://github.com/wbond/package_control_channel/blob/master/repository/r.json#L649

So, it has name "Ruby 1.9 Hash Converter" and does not work in sublime text 3. Installing from git works fine. https://github.com/iltempo/sublime-text-2-hash-syntax/issues/3#issuecomment-22314409

**Comment by kernow** [comment]
I'm still unable to see the version names "Ruby Hash Converter" in package control and had to install using git

**Comment by Alfreddd** [comment]
+1 I don't see "Ruby Hash Converter" in package control

**Comment by meliborn** [comment]
Same thing

**Comment by iltempo** [comment]
Thanks for figuring out. Pull request has been sent.
https://github.com/wbond/package_control_channel/pull/3021
