### ISSUE TITLE
Can't install via PackageControll (doesn't show up)

### ISSUE THREAD

**Issue by Bertg** [iltempo/sublime-text-2-hash-syntax#3]
I'm on the latest ST3 beta, and on the latest PackageControll phyton3 (0a9a9e3).

I've also added the Repository "https://sublime.wbond.net/alpha/packages.json" to Package control. However when I'm trying to find the package; nothing shows up? 

Any advice? (sorry that this might not be an issue of this project, but I don;t know where else to go)

**Comment by bigardone** [comment]
I have the same problem here :(

**Comment by bigardone** [comment]
@Bertg  I finally managed to install it cloning it with git into my Packages folder:

```
git clone -b master git://github.com/iltempo/sublime-text-2-hash-syntax "RubyHashConverter"
```

Now it works like a charm :)

**Comment by tjmcewan** [comment]
thanks @bigardone

**Comment by iltempo** [comment]
Should be fixed with the recent pull request.
https://github.com/wbond/package_control_channel/pull/3021
